name: take_my_tym
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.0
  go_router: ^13.2.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  image_picker: ^1.0.7
  permission_handler:
  emoji_picker_flutter: ^2.1.1
  back_button_interceptor: ^5.0.2
  url_launcher: ^6.2.5
  
  firebase_auth: ^4.17.8
  firebase_core: ^2.26.0
  cloud_firestore: ^4.15.10
  google_sign_in: ^6.2.1

  loading_indicator: ^3.1.1
  flutter_svg: ^2.0.10+1
  animate_do: ^3.3.4
  iconly: ^1.0.1
  lottie: ^3.1.0
  animated_toggle_switch: ^0.8.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/img/auth/
    - asset/img/
    - asset/json/
    - asset/img/test/    
    - asset/img/icons/     


  fonts:
    - family: Poppins
      fonts:
        - asset: asset/font/Poppins/Poppins-Regular.ttf
        - asset: asset/font/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: asset/font/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: asset/font/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: asset/font/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: asset/font/Poppins/Poppins-Black.ttf
          weight: 900

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

